### ISSUE TITLE
💄Limit rules shown to 6

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.People#475]
As per @tiagov8 comment here https://github.com/SSWConsulting/SSW.People/issues/369#issuecomment-1456946329

When a user has a short profile and lots of rules, it doesnt look good

```[tasklist]
### Tasks
- [x] Limit rules count to 6 (or whatever looks best)
```

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/38869720/223293124-e20052bd-f2e6-407d-8d17-6f4cc3523ee8.png">

**Figure: Empty space**

**Comment by tiagov8** [comment]
Hey @BrookJeynes 

I think 5 is even better.

This should be a small one. Can you prioritize?

Cheers,

**Comment by Aibono1225** [comment]
✅ Done - now the widget only shows 5 rules on the page.

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/da7741ef-0cd5-453d-ad6e-da02e3a63f5c)

**Comment by tiagov8** [comment]
cc @bradystroud 

Hi @Aibono1225 

This Issue shows as completed, but profiles are still showing many more than 5 rules... i.e. https://www.ssw.com.au/people/tiago-araujo/

- [ ] 1. Please investigate what happened and fix


![Image](https://github.com/user-attachments/assets/a0cadffb-6fc5-4d3b-8292-69dc6b7e04dc)

**Comment by babakamyljanovssw** [comment]
PR to limit rules count to 5
- https://github.com/SSWConsulting/SSW.People/issues/475
